## Importing the Packages

In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress=True, linewidth=100, precision=2)

## Importing the Data

In [3]:
raw_data = np.genfromtxt("loan-data.csv", delimiter=";", skip_header=True, autostrip=True)
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Checking for Incomplete Data

In [4]:
np.isnan(raw_data).sum()

88005

In [5]:
temp_fill = np.nanmax(raw_data) + 1
temp_mean = np.nanmean(raw_data, axis=0)
raw_data.shape

C:\Users\bhara\AppData\Local\Temp\ipykernel_22252\1504290036.py:2: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(raw_data, axis=0)


(10000, 14)

In [6]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [7]:
temp_stats = np.array([np.nanmin(raw_data, axis=0),
                     temp_mean,
                     np.nanmax(raw_data, axis=0)])

C:\Users\bhara\AppData\Local\Temp\ipykernel_22252\1955102186.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats = np.array([np.nanmin(raw_data, axis=0),
C:\Users\bhara\AppData\Local\Temp\ipykernel_22252\1955102186.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data, axis=0)])


In [8]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting the Dataset

### Splitting the Columns

In [9]:
col_strings = np.argwhere(np.isnan(temp_mean))
col_strings = col_strings.squeeze()
col_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [10]:
col_num = np.argwhere(np.isnan(temp_mean)==False).squeeze()
col_num

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

### Re-importing the Dataset

In [11]:
num_data = np.genfromtxt("loan-data.csv", delimiter=";", skip_header=True, autostrip=True, usecols=(0,  2,  4,  6,  7, 13),
                        filling_values=temp_fill)
num_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [12]:
str_data = np.genfromtxt("loan-data.csv",dtype=str, delimiter=";", skip_header=True, autostrip=True, usecols=col_strings )
str_data

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### The Names of the Columns

In [13]:
headers = np.genfromtxt("loan-data.csv",dtype=str, delimiter=";", skip_footer=raw_data.shape[0], autostrip=True)
headers

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [14]:
num_head, str_head = headers[col_num], headers[col_strings]

In [110]:
num_head

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [16]:
str_head

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

## Creating Checkpoints:

In [17]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [18]:
check_data = checkpoint("Check-test", str_head, str_data)
check_data['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [19]:
check_data['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [20]:
np.array_equal(check_data['data'], str_data)

True

## Manipulating String Columns

In [21]:
str_head

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [22]:
str_head[0] = "issue_date"

In [23]:
str_head
str_data.shape

(10000, 8)

### Issue Date

In [24]:
np.unique(str_data[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [25]:
str_data[:,0] = np.chararray.strip(str_data[:,0],'-15')
np.unique(str_data[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [26]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [27]:
for i in range(13):
        str_data[:,0] = np.where(str_data[:,0] == months[i],
                                          i,
                                          str_data[:,0])

In [28]:
np.unique(str_data[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status

In [29]:
np.unique(str_data[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

We need to convert loan status to numbers
But as per business requirement it is enough to check whether the employee is in good financial status or bad
So grouping loan_status into good: 1 and bad: 0

In [30]:
bad = np.array(['', 'Charged Off','Default','Late (31-120 days)'])

In [31]:
str_data[:,1] = np.where(np.isin(str_data[:,1], bad),0,1)

In [32]:
np.count_nonzero(str_data[:,1]=='0')

687

In [33]:
np.count_nonzero(str_data[:,1]=='1')

9313

### Term

In [34]:
str_head

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [35]:
np.unique(str_data[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [36]:
str_data[:,2] = np.chararray.strip(str_data[:,2]," months")
str_data[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [37]:
str_head[2] = 'term-months'
str_head

array(['issue_date', 'loan_status', 'term-months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

Here we will set empty values = 60, because as per this model if any value is missing then we should assume the worst.

In [38]:
str_data[:,2] = np.where(str_data[:,2]=='',
                        60,
                        str_data[:,2])
np.unique(str_data[:,2])

array(['36', '60'], dtype='<U69')

### Grade and Subgrade

In [39]:
str_head


array(['issue_date', 'loan_status', 'term-months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [40]:
np.unique(str_data[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [41]:
np.unique(str_data[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [42]:
np.unique(str_data[:,3])[1:]

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

#### Filling Sub Grade

In [43]:
for i in np.unique(str_data[:,3])[1:]:
    str_data[:,4] = np.where((str_data[:,4] == '') & (str_data[:,3] == i),
                                      i + '5',
                                      str_data[:,4])

In [44]:
np.unique(str_data[:,4], return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [45]:
str_data[:,4] = np.where(str_data[:,4] == '',
                                      'H1',
                                      str_data[:,4])

In [46]:
np.unique(str_data[:,4], return_counts=True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9],
       dtype=int64))

#### Removing Grade

In [47]:
str_data = np.delete(str_data, 3, axis = 1)

In [48]:
np.unique(str_data[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [49]:
str_head = np.delete(str_head, 3)

In [50]:
str_head[3]

'sub_grade'

#### Converting Sub Grade

In [51]:
np.unique(str_data[:,3]).shape

(36,)

In [52]:
keys = list(np.unique(str_data[:,3]))                         
values = list(range(1, np.unique(str_data[:,3]).shape[0] + 1)) 
dict_sub_grade = dict(zip(keys, values))

In [53]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [54]:
for i in np.unique(str_data[:,3]):
        str_data[:,3] = np.where(str_data[:,3] == i, 
                                          dict_sub_grade[i],
                                          str_data[:,3])

In [55]:
np.unique(str_data[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification Status

In [56]:
str_head

array(['issue_date', 'loan_status', 'term-months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [57]:
np.unique(str_data[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [58]:
str_data[:,4] = np.where((str_data[:,4]=='') | (str_data[:,4]=='Not Verified'),0,1)

In [59]:
np.unique(str_data[:,4])

array(['0', '1'], dtype='<U69')

### URL

In [60]:
np.unique(str_data[:,5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'], dtype='<U69')

In [61]:
str_data[:,5] = np.chararray.strip(str_data[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [62]:
str_data[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [63]:
headers

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [64]:
num_data[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [65]:
str_data[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [66]:
np.array_equal(num_data[:,0].astype(dtype = np.int32), str_data[:,5].astype(dtype = np.int32))

True

Both id and URL columns are same, so deleting URL

In [67]:
str_data = np.delete(str_data,5,axis=1)
str_head = np.delete(str_head,5)

In [68]:
str_data[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

### State Address

In [69]:
str_head

array(['issue_date', 'loan_status', 'term-months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [70]:
str_head[5] = "state_address"

In [71]:
states_names, states_count = np.unique(str_data[:,5], return_counts = True)
states_count_sorted = np.argsort(-states_count)
states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [72]:
str_data[:,5] = np.where(str_data[:,5]=='',
                        0,
                        str_data[:,5])

In [73]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [74]:
str_data[:,5] = np.where(np.isin(str_data[:,5], states_west),1,str_data[:,5])
str_data[:,5] = np.where(np.isin(str_data[:,5], states_south),2,str_data[:,5])
str_data[:,5] = np.where(np.isin(str_data[:,5], states_midwest),3,str_data[:,5])
str_data[:,5] = np.where(np.isin(str_data[:,5], states_east),4,str_data[:,5])


In [75]:
np.unique(str_data[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Converting to Numbers

In [76]:
str_data


array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [77]:
str_data = str_data.astype(int)

In [78]:
str_data

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

### Checkpoint 1: Strings

In [144]:
checkpoint_str = checkpoint("Checkpoint-strings", str_head, str_data)

In [146]:
checkpoint_str['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [147]:
checkpoint_str['header']

array(['issue_date', 'loan_status', 'term-months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

## Manipulating Numeric Columns

In [82]:
num_head

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [83]:
num_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### Substitute "Filler" Values

#### ID

In [84]:
temp_fill

68616520.0

In [85]:
np.isin(num_data[:,0],temp_fill).sum()

0

In [86]:
col_num

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

#### Temporary Stats

In [87]:
temp_num_stats = temp_stats[:,col_num]
temp_num_stats

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

#### Funded Amount

In [88]:
num_head

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [89]:
num_data[:,2] = np.where(num_data[:,2] == temp_fill, 
                                  temp_num_stats[0,2],
                                  num_data[:,2])
num_data[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

#### Loaned Amount, Interest Rate, Total Payment, Installment

In [90]:
num_head

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [91]:
for i in [1,3,4,5]:
    num_data[:,i] = np.where(num_data[:,i] == temp_fill, 
                                  temp_num_stats[2,i],
                                  num_data[:,i])

In [92]:
num_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

### Currency Change

#### The Exchange Rate

In [93]:
#EUR-USD.csv consists of exchange rate for every month in orderly fashion
EUR_USD = np.genfromtxt("EUR-USD.csv", delimiter = ',', autostrip = True, skip_header = 1, usecols = 3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [94]:
str_head[0]

'issue_date'

In [95]:
exchange_rate = str_data[:,0]
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1],
                             exchange_rate)    
exchange_rate = np.where(exchange_rate == 0,
                         np.mean(EUR_USD),
                         exchange_rate)

exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

Now we need to add exchange rate column in num_data

In [96]:
exchange_rate.shape

(10000,)

In [97]:
num_data.shape

(10000, 6)

In [98]:
exchange_rate = np.reshape(exchange_rate, (10000,1))
exchange_rate

array([[1.1 ],
       [1.11],
       [1.13],
       ...,
       [1.12],
       [1.11],
       [1.09]])

In [99]:
num_data = np.hstack((num_data,exchange_rate))

In [100]:
num_head = np.concatenate((num_head, np.array(['exchange_rate'])))
num_head

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

#### From USD to EUR

In [102]:
num_head

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [103]:
columns_dollar = np.array([1,2,4,5])

In [105]:
num_data[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [106]:
for i in columns_dollar:
    num_data = np.hstack((num_data, np.reshape(num_data[:,i] / num_data[:,6], (10000,1))))

In [107]:
num_data.shape

(10000, 11)

In [111]:
num_head

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

#### Expanding the header

In [109]:
header_additional = np.array([column_name + '_EUR' for column_name in num_head[columns_dollar]])

In [113]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [117]:
num_head = np.concatenate((num_head, header_additional))

In [118]:
num_head

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [119]:
num_head[columns_dollar] = np.array([column_name + '_USD' for column_name in num_head[columns_dollar]])

In [120]:
num_head

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [121]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [122]:
num_head = num_head[columns_index_order]

In [123]:
num_head

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [125]:
num_data = num_data[:,columns_index_order]

In [126]:
num_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

### Interest Rate

In [127]:
num_head

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [128]:
num_data[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [129]:
num_data[:,5] = num_data[:,5]/100

In [130]:
num_data[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### Checkpoint 2: Numeric

In [131]:
checkpoint_numeric = checkpoint("Checkpoint-Numeric", num_head, num_data)

In [132]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

## Creating the "Complete" Dataset

In [137]:
checkpoint_str['data'].shape

(10000, 6)

In [138]:
checkpoint_numeric['data'].shape

(10000, 11)

In [140]:
loan_data = np.hstack((checkpoint_str['data'], checkpoint_numeric['data']))

In [141]:
loan_data

array([[   5.  ,    1.  ,   36.  , ..., 9452.96, 8624.69,    1.1 ],
       [   0.  ,    1.  ,   36.  , ..., 4679.7 , 4232.39,    1.11],
       [   9.  ,    1.  ,   36.  , ..., 1969.83, 1750.04,    1.13],
       ...,
       [   6.  ,    1.  ,   36.  , ..., 2185.64, 1947.47,    1.12],
       [   4.  ,    1.  ,   36.  , ..., 3199.4 , 2878.63,    1.11],
       [  12.  ,    1.  ,   36.  , ...,  301.9 ,  276.11,    1.09]])

In [148]:
header_full = np.concatenate((checkpoint_str['header'], checkpoint_numeric['header']))

In [149]:
header_full

array(['issue_date', 'loan_status', 'term-months', 'sub_grade', 'verification_status',
       'state_address', 'id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD',
       'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD',
       'total_pymnt_EUR', 'exchange_rate'], dtype='<U19')

## Sorting the New Dataset

In [151]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [152]:
loan_data

array([[   0.  ,    1.  ,   36.  , ..., 6770.56, 6123.4 ,    1.11],
       [   0.  ,    1.  ,   60.  , ...,    0.  ,    0.  ,    1.11],
       [   0.  ,    1.  ,   36.  , ..., 2208.92, 1997.78,    1.11],
       ...,
       [  12.  ,    1.  ,   36.  , ...,  665.17,  608.35,    1.09],
       [  12.  ,    1.  ,   36.  , ...,    0.  ,    0.  ,    1.09],
       [  12.  ,    1.  ,   36.  , ...,  301.9 ,  276.11,    1.09]])

In [158]:
np.argsort(loan_data[:,0])

array([   0,  341,  340, ..., 9342, 9329, 9999], dtype=int64)

## Storing the New Dataset

In [159]:
loan_data = np.vstack((header_full, loan_data))

In [160]:
loan_data.head()

array([['issue_date', 'loan_status', 'term-months', ..., 'total_pymnt_USD', 'total_pymnt_EUR',
        'exchange_rate'],
       ['0.0', '1.0', '36.0', ..., '6770.56', '6123.398277641691', '1.1056866943836212'],
       ['0.0', '1.0', '60.0', ..., '0.0', '0.0', '1.1056866943836212'],
       ...,
       ['12.0', '1.0', '36.0', ..., '665.17', '608.3511609744695', '1.093398094177246'],
       ['12.0', '1.0', '36.0', ..., '0.0', '0.0', '1.093398094177246'],
       ['12.0', '1.0', '36.0', ..., '301.9', '276.11169400031923', '1.093398094177246']],
      dtype='<U32')